---
- hosts: all
  tasks:
  
  - name: ensure a directory exists
    file:
      path: "$HOME/{{ item }}"
      state: directory
    loop:
      - test_directory1
      - test_directory2
      - test_directory3
    become: true

  - name: Creating file
    file:
      path: "$HOME/file.txt"
      state: touch
  - name: change directory permissions
    file: 
      path: "$HOME/test_directory1"
      state: directory
      owner: root
      group: root
      mode: 400
    become: true
     