---
- name: configure DB server
  hosts: db_servers
  become: yes

  tasks:
    - name: Install MySQL server
      ansible.builtin.apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Start and enable MySQL server
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
